image:
  repository: ghcr.io/yang-yang9/transitmonitor
  tag: v0.0.1
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 7421
resources:
  limits: {cpu: 200m, memory: 256Mi}
  requests: {cpu: 50m, memory: 64Mi}
config: |
  # paste your config.yaml content here
encryptionKey: ""
dashboardToken: ""
